name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --ignore-scripts
      - run: npm run build
        name: Build
      - run: npm test
        env:
          CI: true
      - uses: codecov/codecov-action@v2
        with:
          name: codecov
          directory: ./coverage/
          flags: unittests
