name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: rustup target add wasm32-unknown-unknown
      - run: npm ci --ignore-scripts
      - run: npm run build
      - run: npm test
        env:
          CI: true
      - run: npm run docs
      - uses: codecov/codecov-action@v2
        with:
          name: codecov
          directory: ./coverage/
          flags: unittests
